### ISSUE TITLE
SeeShark fails due to missing postproc

### ISSUE THREAD

**Issue by dbruning** [vignetteapp/SeeShark#15]
Postproc library is GPL and is not included in some LGPL builds of FFmpeg libraries.
In SeeShark, FFmpegManager is checking the requested libraries, and all their dependencies. 
FFmpeg.Autogen defines postproc as a dependency of avfilter
Therefore, SeeShark effectively requires postproc. I think that postproc is kind of an optional dependency; it still runs if I comment out the checking of dependencies.

As a fix, you could simply not check the dependencies - just check the top-level libraries. Or, you could allow postproc to not be found without throwing an error.

**Comment by sr229** [comment]
Yikes, nice catch, looks like we did not compensate for that, we'll see what we can do :D

**Comment by Speykious** [comment]
Hmmm. That's weird, all I did was copy the dependencies from FFmpeg.AutoGen iirc.
The problem might need to be forwarded there. I'll investigate.

**Comment by Speykious** [comment]
Ok I think I misunderstood for some reason. Indeed *FFmpeg.AutoGen* defines postproc as a dependency of avfilter as you said.
But then yeah, I don't understand how FFmpeg.AutoGen defines "dependency". That ambiguity is what might need to be forwarded.

**Comment by Speykious** [comment]
Update: from the looks of it, dependencies were made optional in FFmpeg.AutoGen since the following commit:
https://github.com/Ruslan-B/FFmpeg.AutoGen/commit/395dea80c642c85e089e3d7721f91d77594655c1#
after the issue had been raised here: https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/137

Looks like I didn't understand the code properly and I'll have to fix it indeed.

**Comment by sr229** [comment]
Fixed by c223bc9 (hopefully).
